Use HTML5 instead of HTML4
Vertispan/j2clmavenplugin pull request #156
Opened 2022-04-17 11:06 UTC by andirady

Since HTML5 is now the standard, I believe the HTML files shouldn't use HTML4 anymore.

2022-04-17 15:58 UTC, niloc132 commented
Thanks for the change - it is slightly more concise, so I'm happy to merge it, but I do believe these result in the same behavior by browsers. While the new doctype you've given is the doctype specified by html5, it is not an html5 doctype, just an "html" doctype, suitable for all modern html.

2022-04-17 15:58 UTC, niloc132 approved these changes

2022-04-17 16:03 UTC, niloc132 requested changes
Actually, it looks junit.html could also be updated in this way, would you mind making that change in this same PR?

2022-04-18 14:49 UTC, andirady commented
> Actually, it looks junit.html could also be updated in this way, would you mind making that change in this same PR?

Done.

2022-04-18 19:14 UTC, niloc132 approved these changes

2022-04-18 22:30 UTC, merged