Suppressed ClosedWatchServiceException and updated Java of Archetypes to 11 #188
Vertispan/j2clmavenplugin pull request #231
Opened 2023-08-31 02:41 UTC by jiakuan

Fixes for #188

2023-08-31 14:27 UTC, niloc132 commented
CI is giving us some grief, usually it is closer to 5% failure rate (something in the resource constrained env seems to make it easy to hit a race condition when evaluating unit tests in a sample maven project...). I'll look more closely at the output here when I get the chance and confirm we're not actually hitting a real bug of some kind, then get this PR merged.

2023-09-28 01:36 UTC, treblereel commented on build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java
> +            // This is purely noise in the log and doesn't indicate an actual
```suggestion
            if(!livenessThread.getState().equals(Thread.State.TERMINATED)) {
                 throw new Error(e);
            }

            // This is purely noise in the log and doesn't indicate an actual
```

2023-09-28 01:47 UTC, treblereel requested changes

2023-09-28 01:47 UTC, treblereel commented on build-caching/src/main/java/com/vertispan/j2cl/build/DiskCache.java
> +            // This is purely noise in the log and doesn't indicate an actual
I think that we can add an additional check to ensure that this exception is thrown only when the build is complete. This is necessary to rule out other scenarios.

2023-09-28 01:49 UTC, treblereel commented
> CI is giving us some grief, usually it is closer to 5% failure rate (something in the resource constrained env seems to make it easy to hit a race condition when evaluating unit tests in a sample maven project...). I'll look more closely at the output here when I get the chance and confirm we're not actually hitting a real bug of some kind, then get this PR merged.

in my case, on osx each build ends with this exception.

2023-09-30 22:23 UTC, treblereel approved these changes
It's good to go.
Thanks!

2023-11-05 00:55 UTC, merged